import test from "node:test"; import assert from "node:assert/strict";
import { assertSalesDraftReady, isMeaningfulSalesDraft, markDraft, newSalesDraft, recoverInterruptedDraft, setDraftItem, switchDraftCustomer } from "../src/products/sales/domain";

test("sales drafts keep one quantity per item and remove zero quantities",()=>{let d=newSalesDraft("Main",new Date("2026-07-15T00:00:00Z"));d={...d,customer:"CUST-1"};d=setDraftItem(d,{item_code:"ITEM-1",qty:2,uom:"Nos"});d=setDraftItem(d,{item_code:"ITEM-1",qty:4,uom:"Nos"});assert.equal(d.items.length,1);assert.equal(d.items[0].qty,4);d=setDraftItem(d,{item_code:"ITEM-1",qty:0});assert.equal(d.items.length,0)});
test("ready sales draft requires warehouse and customer but not an Ai Matic branch",()=>{const d={...newSalesDraft("",new Date(),"Stores - TC"),customer:"CUST-1",items:[{item_code:"ITEM-1",qty:1}]};assert.doesNotThrow(()=>assertSalesDraftReady(d));assert.throws(()=>assertSalesDraftReady({...d,customer:""}),/Customer and warehouse/);assert.throws(()=>assertSalesDraftReady({...d,warehouse:""}),/Customer and warehouse/)});
test("queued draft preserves its idempotency request id",()=>{const d=newSalesDraft("Main");const queued=markDraft(d,"queued",{error:"offline"});assert.equal(queued.requestId,d.requestId);assert.equal(queued.status,"queued")});
test("empty active sales draft does not pollute the drafts list",()=>{const empty=newSalesDraft();assert.equal(isMeaningfulSalesDraft(empty),false);assert.equal(isMeaningfulSalesDraft({...empty,customer:"CUST-1"}),true)});
test("an interrupted syncing draft safely returns to the queue",()=>{const draft=markDraft(newSalesDraft(),"syncing");const recovered=recoverInterruptedDraft(draft);assert.equal(recovered.status,"queued");assert.match(recovered.error||"",/interrupted/i);assert.equal(recovered.requestId,draft.requestId)});
test("switching to a different customer clears items priced under the previous customer",()=>{let d=newSalesDraft("Main");d={...d,customer:"CUST-1"};d=setDraftItem(d,{item_code:"ITEM-1",qty:2,uom:"Nos"});d=switchDraftCustomer(d,"CUST-2");assert.equal(d.customer,"CUST-2");assert.equal(d.items.length,0)});
test("re-selecting the same customer keeps the cart intact",()=>{let d=newSalesDraft("Main");d={...d,customer:"CUST-1"};d=setDraftItem(d,{item_code:"ITEM-1",qty:2,uom:"Nos"});d=switchDraftCustomer(d,"CUST-1");assert.equal(d.items.length,1);assert.equal(d.items[0].item_code,"ITEM-1")});
test("switching customer clears the previous delivery location",()=>{let d={...newSalesDraft("Main"),customer:"CUST-1",deliveryLocation:"LOC-1"};d=switchDraftCustomer(d,"CUST-2");assert.equal(d.deliveryLocation,"")});
test("re-selecting the same customer preserves its delivery location",()=>{let d={...newSalesDraft("Main"),customer:"CUST-1",deliveryLocation:"LOC-1"};d=switchDraftCustomer(d,"CUST-1");assert.equal(d.deliveryLocation,"LOC-1")});
test("switching customer clears discount request context",()=>{let d={...newSalesDraft("Main"),customer:"CUST-1",discountPercent:12,discountReason:"Tender match"};d=switchDraftCustomer(d,"CUST-2");assert.equal(d.discountPercent,0);assert.equal(d.discountReason,"")});
test("re-selecting the same customer preserves discount request context",()=>{let d={...newSalesDraft("Main"),customer:"CUST-1",discountPercent:5,discountReason:"Contract"};d=switchDraftCustomer(d,"CUST-1");assert.equal(d.discountPercent,5);assert.equal(d.discountReason,"Contract")});
