import { createApiClient } from "../../api/client";
import { createSalesOrdersApi } from "../../api/sales-orders";
import { capacitorOAuthBrowser } from "../../mobile/capacitor-oauth-browser";
import { OAuthPkceCredentialProvider, type OAuthPublicClientConfig } from "../../mobile/credential-provider";
import { scanItemBarcode } from "../../mobile/item-barcode-scanner";
import { androidSecureStorage } from "../../mobile/secure-storage";
import { assertSalesDraftReady, markDraft, newSalesDraft, setDraftItem, type SalesDraft } from "./domain";

declare const __APP_VERSION__: string;
type Row=Record<string,unknown>; type Screen="order"|"drafts"|"history";
const root=document.querySelector<HTMLElement>("#app")!; const fetcher=globalThis.fetch.bind(globalThis);
const configKey="aimatic-sales-config-v1", draftsKey="aimatic-sales-drafts-v1";
let config:OAuthPublicClientConfig|null=null, credentials:OAuthPkceCredentialProvider|null=null, api:ReturnType<typeof createSalesOrdersApi>|null=null;
let context:Row={}, customer:Row|null=null, customers:Row[]=[], products:Row[]=[], history:Row[]=[], screen:Screen="order", message="", draft=newSalesDraft(), preview:Row|null=null;
const esc=(v:unknown)=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]!));
const text=(r:Row|undefined,...keys:string[])=>{for(const k of keys)if(r?.[k]!=null)return String(r[k]);return""};
const list=(v:unknown):Row[]=>Array.isArray(v)?v.filter((x):x is Row=>!!x&&typeof x==="object"):[];
const money=(v:unknown)=>`${text(preview||context,"currency")||"PKR"} ${Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
async function payload(response:Response){const raw=await response.json().catch(()=>({})) as Row;const value=(raw.message&&typeof raw.message==="object"?raw.message:raw) as Row;if(!response.ok)throw new Error(text(value,"message","exception")||`Server error ${response.status}`);return value}
function loadDrafts():SalesDraft[]{try{return JSON.parse(localStorage.getItem(draftsKey)||"[]") as SalesDraft[]}catch{return[]}}
function save(value:SalesDraft){const all=[value,...loadDrafts().filter(x=>x.requestId!==value.requestId)];localStorage.setItem(draftsKey,JSON.stringify(all));draft=value}
async function configure(baseUrl:string){const url=baseUrl.replace(/\/+$/,"");const pub=await payload(await fetcher(`${url}/api/method/aimatic.mobile_sales.api.get_public_config`,{method:"POST"}));config={baseUrl:url,clientId:text(pub,"oauth_client_id"),redirectUri:text(pub,"redirect_uri"),scope:text(pub,"scope")};if(!config.clientId||!config.redirectUri)throw new Error("Sales OAuth is not configured.");localStorage.setItem(configKey,JSON.stringify(config));credentials=new OAuthPkceCredentialProvider(async()=>config!,androidSecureStorage,capacitorOAuthBrowser,fetcher);api=createSalesOrdersApi(createApiClient({baseUrl:url,authentication:{mode:"user-session",credentials},fetch:fetcher}));}
async function start(){const raw=localStorage.getItem(configKey);if(!raw)return setup();try{await configure((JSON.parse(raw) as OAuthPublicClientConfig).baseUrl);if(!await credentials!.getAccessToken())return signIn();await loadContext()}catch(e){setup(e instanceof Error?e.message:"Unable to start")}}
function setup(error=""){root.innerHTML=`<section class="setup"><div class="card"><h1>Ai Matic Sales</h1><p>Connect this salesperson app to ERPNext.</p>${error?`<p class="error">${esc(error)}</p>`:""}<form id="setup"><label>ERPNext URL<input id="url" type="url" required placeholder="https://erp.example.com"></label><br><button class="primary">Continue</button></form><p class="muted">v${esc(__APP_VERSION__)} · No API key or API secret</p></div></section>`;document.querySelector<HTMLFormElement>("#setup")!.onsubmit=async e=>{e.preventDefault();try{await configure(document.querySelector<HTMLInputElement>("#url")!.value);signIn()}catch(x){setup(x instanceof Error?x.message:"Connection failed")}}}
function signIn(){root.innerHTML=`<section class="setup"><div class="card"><h1>Salesperson sign in</h1><p>Use your individual ERPNext Sales User account.</p>${message?`<p class="error">${esc(message)}</p>`:""}<button id="login" class="primary">Sign in with ERPNext</button></div></section>`;document.querySelector<HTMLButtonElement>("#login")!.onclick=async()=>{try{await credentials!.login();await loadContext()}catch(e){message=e instanceof Error?e.message:"Sign in failed";signIn()}}}
async function loadContext(){context=await payload(await api!.getContext());draft.branch ||= text(context,"branch");save(draft);await syncQueued();render("order")}
async function findCustomers(query:string){customers=list((await payload(await api!.searchCustomers(query))).customers);render("order")}
async function selectCustomer(name:string){customer=await payload(await api!.getCustomerContext(name,draft.branch));draft={...draft,customer:name};save(draft);customers=[];preview=null;render("order")}
async function findItems(query="",barcode=""){products=list((await payload(await api!.searchItems({branch:draft.branch,customer:draft.customer,search:query||undefined,barcode:barcode||undefined}))).items);render("order")}
function orderView(){const total=draft.items.reduce((n,x)=>n+Number(products.find(p=>text(p,"name")===x.item_code)?.rate||0)*x.qty,0);return `<div class="card"><div class="grid"><label>Branch<select id="branch">${list(context.branches).map(b=>`<option ${text(b,"name")===draft.branch?"selected":""}>${esc(text(b,"name"))}</option>`).join("")}</select></label><label>Delivery date<input id="delivery" type="date" value="${esc(draft.deliveryDate)}"></label></div></div><div class="card"><h2>Customer</h2>${customer?`<div class="row"><div><h3>${esc(text(customer,"customer_name","name"))}</h3><p>${esc(text(customer,"price_list"))}</p></div><div><p class="money">Outstanding ${money(customer.outstanding_balance)}</p><p>Credit limit ${money(customer.credit_limit)}</p></div></div><button id="change-customer" class="secondary">Change customer</button>`:`<div class="search"><input id="customer-query" placeholder="Name, mobile or email"><button id="customer-search" class="secondary">Search</button></div>${customers.map(x=>`<button class="row customer" data-name="${esc(text(x,"name"))}"><span>${esc(text(x,"customer_name","name"))}</span><span>${esc(text(x,"mobile_no"))}</span></button>`).join("")}`}</div><div class="card"><h2>Items</h2><div class="actions"><div class="search"><input id="item-query" placeholder="Search item"><button id="item-search" class="secondary">Search</button></div><button id="scan" class="secondary">Scan barcode</button></div>${products.map(p=>`<div class="row"><div><h3>${esc(text(p,"item_name","name"))}</h3><p>${money(p.rate)} · Available ${esc(p.available_qty)}</p></div><button class="primary add" data-code="${esc(text(p,"name"))}">Add</button></div>`).join("")}</div><div class="card"><h2>Order cart</h2>${draft.items.map(i=>`<div class="row"><div><h3>${esc(i.item_code)}</h3><p>${esc(i.uom||"")}</p></div><input class="qty" data-code="${esc(i.item_code)}" type="number" min="0" step="0.001" value="${esc(i.qty)}"></div>`).join("")||"<p class=\"muted\">No items added.</p>"}<p class="summary"><span>Displayed estimate</span><b>${money(total)}</b></p><div class="grid"><label>Customer PO<input id="po" value="${esc(draft.poNo)}"></label><label>Notes<textarea id="remarks">${esc(draft.remarks)}</textarea></label></div>${preview?.credit_warning?`<p class="warning">Credit limit warning: ERPNext will enforce its validation when the order is processed.</p>`:""}${preview?`<p class="summary"><span>ERPNext total</span><b>${money(preview.grand_total)}</b></p>`:""}<div class="actions"><button id="save-draft" class="secondary">Save offline draft</button><button id="preview" class="secondary">Refresh ERPNext total</button><button id="submit" class="primary">Create Sales Order</button></div></div>`}
function draftsView(){return `<div class="card"><h2>Offline drafts and queue</h2>${loadDrafts().map(d=>`<div class="row"><div><b>${esc(d.customer||"Unassigned draft")}</b><p>${esc(d.status)} · ${esc(d.items.length)} items${d.error?` · ${esc(d.error)}`:""}</p></div><button class="secondary load" data-id="${esc(d.requestId)}">Open</button></div>`).join("")||"<p>No saved drafts.</p>"}<button id="sync" class="primary">Sync queued orders</button></div>`}
function historyView(){return `<div class="card"><h2>Sales Order history</h2>${history.map(o=>`<div class="row"><div><b>${esc(text(o,"name"))}</b><p>${esc(text(o,"customer_name","customer"))} · ${esc(text(o,"status"))}</p></div><b>${money(o.grand_total)}</b></div>`).join("")||"<p>No orders loaded.</p>"}</div>`}
function render(next:Screen=screen){screen=next;root.innerHTML=`<header class="top"><h1>Ai Matic Sales</h1><span>${esc(text(context,"full_name","user"))}</span></header><section class="page">${message?`<p class="${message.startsWith("Order ")?"success":"error"}">${esc(message)}</p>`:""}${screen==="order"?orderView():screen==="drafts"?draftsView():historyView()}</section><nav class="nav" aria-label="Sales navigation"><button data-screen="order" ${screen==="order"?'aria-current="page"':""}>New order</button><button data-screen="drafts" ${screen==="drafts"?'aria-current="page"':""}>Drafts</button><button data-screen="history" ${screen==="history"?'aria-current="page"':""}>History</button></nav>`;bind()}
function updateForm(){draft={...draft,branch:(document.querySelector<HTMLSelectElement>("#branch")?.value||draft.branch),deliveryDate:document.querySelector<HTMLInputElement>("#delivery")?.value||draft.deliveryDate,poNo:document.querySelector<HTMLInputElement>("#po")?.value||"",remarks:document.querySelector<HTMLTextAreaElement>("#remarks")?.value||""};save(draft)}
function bind(){document.querySelectorAll<HTMLButtonElement>("[data-screen]").forEach(b=>b.onclick=async()=>{const s=b.dataset.screen as Screen;if(s==="history")history=list((await payload(await api!.getOrders())).orders);render(s)});document.querySelector<HTMLSelectElement>("#branch")?.addEventListener("change",()=>{updateForm();customer=null;draft.customer="";preview=null;save(draft);render()});document.querySelector<HTMLButtonElement>("#customer-search")?.addEventListener("click",()=>void findCustomers(document.querySelector<HTMLInputElement>("#customer-query")!.value));document.querySelectorAll<HTMLButtonElement>(".customer").forEach(b=>b.onclick=()=>void selectCustomer(b.dataset.name!));document.querySelector<HTMLButtonElement>("#change-customer")?.addEventListener("click",()=>{customer=null;draft.customer="";save(draft);render()});document.querySelector<HTMLButtonElement>("#item-search")?.addEventListener("click",()=>void findItems(document.querySelector<HTMLInputElement>("#item-query")!.value));document.querySelector<HTMLButtonElement>("#scan")?.addEventListener("click",async()=>{try{await findItems("",await scanItemBarcode())}catch(e){message=e instanceof Error?e.message:"Scan failed";render()}});document.querySelectorAll<HTMLButtonElement>(".add").forEach(b=>b.onclick=()=>{const p=products.find(x=>text(x,"name")===b.dataset.code)!;draft=setDraftItem(draft,{item_code:text(p,"name"),qty:1,uom:text(p,"stock_uom")});save(draft);render()});document.querySelectorAll<HTMLInputElement>(".qty").forEach(i=>i.onchange=()=>{const old=draft.items.find(x=>x.item_code===i.dataset.code)!;draft=setDraftItem(draft,{...old,qty:Number(i.value)});save(draft);render()});document.querySelector<HTMLButtonElement>("#save-draft")?.addEventListener("click",()=>{updateForm();message="Draft saved on this device.";render()});document.querySelector<HTMLButtonElement>("#preview")?.addEventListener("click",()=>void previewOrder());document.querySelector<HTMLButtonElement>("#submit")?.addEventListener("click",()=>void submitOrder());document.querySelectorAll<HTMLButtonElement>(".load").forEach(b=>b.onclick=()=>{draft=loadDrafts().find(x=>x.requestId===b.dataset.id)!;customer=null;message="";render("order")});document.querySelector<HTMLButtonElement>("#sync")?.addEventListener("click",()=>void syncQueued(true))}
function requestBody(d:SalesDraft){return{request_id:d.requestId,branch:d.branch,customer:d.customer,items:d.items,delivery_date:d.deliveryDate,po_no:d.poNo,remarks:d.remarks}}
async function previewOrder(){try{updateForm();assertSalesDraftReady(draft);preview=await payload(await api!.previewOrder(requestBody(draft)));message="";render()}catch(e){message=e instanceof Error?e.message:"Preview failed";render()}}
async function submitOrder(){try{updateForm();assertSalesDraftReady(draft);const result=await payload(await api!.createOrder(requestBody(draft)));save(markDraft(draft,"submitted",{salesOrder:text(result,"sales_order")}));message=`Order ${text(result,"sales_order")} created.`;preview=null;draft=newSalesDraft(text(context,"branch"));save(draft);render()}catch(e){const error=e instanceof Error?e.message:"Network error";save(markDraft(draft,navigator.onLine?"failed":"queued",{error}));message=navigator.onLine?error:"Order queued and will sync when online.";render()}}
async function syncQueued(show=false){let count=0;for(const d of loadDrafts().filter(x=>x.status==="queued")){try{const result=await payload(await api!.createOrder(requestBody(d)));save(markDraft(d,"submitted",{salesOrder:text(result,"sales_order"),error:undefined}));count++}catch{/* keep queued */}}if(show){message=`Synced ${count} queued order${count===1?"":"s"}.`;render("drafts")}}
void start();
