import { createApiClient } from "../../api/client";
import { createSalesOrdersApi } from "../../api/sales-orders";
import { capacitorOAuthBrowser } from "../../mobile/capacitor-oauth-browser";
import { OAuthPkceCredentialProvider, type OAuthPublicClientConfig } from "../../mobile/credential-provider";
import { scanItemBarcode } from "../../mobile/item-barcode-scanner";
import { androidSecureStorage } from "../../mobile/secure-storage";
import { bottomNavigation, emptyState, escapeHtml as esc, formatMoney, loadingSkeleton, statusBadge, type UiTone } from "../shared/ui";
import { assertSalesDraftReady, isMeaningfulSalesDraft, markDraft, newSalesDraft, recoverInterruptedDraft, setDraftItem, switchDraftCustomer, type SalesDraft } from "./domain";

declare const __APP_VERSION__: string;
type Row=Record<string,unknown>;
type Screen="customers"|"order"|"review"|"drafts"|"orders"|"profile";

const root=document.querySelector<HTMLElement>("#app")!;
const fetcher=globalThis.fetch.bind(globalThis);
const configKey="aimatic-sales-config-v1",draftsKey="aimatic-sales-drafts-v1",activeDraftKey="aimatic-sales-active-draft-v2",recentCustomersKey="aimatic-sales-recent-customers-v1",recentItemsKey="aimatic-sales-recent-items-v1";
let config:OAuthPublicClientConfig|null=null,credentials:OAuthPkceCredentialProvider|null=null,api:ReturnType<typeof createSalesOrdersApi>|null=null;
let context:Row={},customer:Row|null=null,customers:Row[]=[],products:Row[]=[],history:Row[]=[],screen:Screen="customers";
let message="",messageTone:UiTone="neutral",draft=loadActiveDraft(),preview:Row|null=null,loading="",category="All",orderFilter="All",searchTimer=0;
let draftStore:SalesDraft[]|null=null,itemIndex=new Map<string,Row>(),itemSearchSequence=0,customerSearchSequence=0,lastItemSearch="",customerQuery="",itemQuery="";
let syncPromise:Promise<void>|null=null,submitting=false;

const text=(row:Row|undefined,...keys:string[])=>{for(const key of keys)if(row?.[key]!=null)return String(row[key]);return""};
const list=(value:unknown):Row[]=>Array.isArray(value)?value.filter((entry):entry is Row=>Boolean(entry)&&typeof entry==="object"):[];
const currency=()=>text(preview||context,"currency")||"PKR";
const money=(value:unknown)=>formatMoney(value,currency());
const readList=(key:string):string[]=>{try{const value=JSON.parse(localStorage.getItem(key)||"[]");return Array.isArray(value)?value.map(String):[]}catch{return[]}};
const remember=(key:string,value:string)=>localStorage.setItem(key,JSON.stringify([value,...readList(key).filter((entry)=>entry!==value)].slice(0,6)));
async function payload(response:Response){const raw=await response.json().catch(()=>({})) as Row;const value=(raw.message&&typeof raw.message==="object"?raw.message:raw) as Row;if(!response.ok)throw new Error(text(value,"message","exception")||`Server error ${response.status}`);return value}
function loadActiveDraft():SalesDraft{try{const saved=JSON.parse(localStorage.getItem(activeDraftKey)||"null") as SalesDraft|null;return saved?recoverInterruptedDraft({...saved,warehouse:saved.warehouse||""}):newSalesDraft()}catch{return newSalesDraft()}}
function loadDrafts():SalesDraft[]{if(draftStore)return draftStore;try{const saved=JSON.parse(localStorage.getItem(draftsKey)||"[]") as SalesDraft[];draftStore=saved.map((entry)=>recoverInterruptedDraft({...entry,warehouse:entry.warehouse||""})).filter(isMeaningfulSalesDraft);localStorage.setItem(draftsKey,JSON.stringify(draftStore));return draftStore}catch{draftStore=[];return draftStore}}
function save(value:SalesDraft,activate=true){const others=loadDrafts().filter((entry)=>entry.requestId!==value.requestId);draftStore=isMeaningfulSalesDraft(value)?[value,...others]:others;localStorage.setItem(draftsKey,JSON.stringify(draftStore));if(activate){draft=value;localStorage.setItem(activeDraftKey,JSON.stringify(value))}}
function notice(value:string,tone:UiTone="neutral"){message=value;messageTone=tone}
function statusTone(status:string):UiTone{return status==="submitted"||status==="Completed"?"success":status==="queued"||status==="syncing"||status==="Draft"?"warning":status==="failed"||status==="Cancelled"?"danger":"info"}
function itemRate(code:string):number{return Number(itemIndex.get(code)?.rate||0)}
function estimate():number{return draft.items.reduce((total,item)=>total+itemRate(item.item_code)*item.qty,0)}
function currentCustomerName():string{return text(customer||undefined,"customer_name","name")||draft.customer}

async function configure(baseUrl:string){
  const url=baseUrl.replace(/\/+$/,"");
  const pub=await payload(await fetcher(`${url}/api/method/aimatic.mobile_sales.api.get_public_config`,{method:"POST"}));
  config={baseUrl:url,clientId:text(pub,"oauth_client_id"),redirectUri:text(pub,"redirect_uri"),scope:text(pub,"scope")};
  if(!config.clientId||!config.redirectUri)throw new Error("Sales OAuth is not configured.");
  localStorage.setItem(configKey,JSON.stringify(config));
  credentials=new OAuthPkceCredentialProvider(async()=>config!,androidSecureStorage,capacitorOAuthBrowser,fetcher);
  api=createSalesOrdersApi(createApiClient({baseUrl:url,authentication:{mode:"user-session",credentials},fetch:fetcher}));
}
async function start(){const raw=localStorage.getItem(configKey);if(!raw)return setup();try{await configure((JSON.parse(raw) as OAuthPublicClientConfig).baseUrl);if(!await credentials!.getAccessToken())return signIn();await loadContext()}catch(error){setup(error instanceof Error?error.message:"Unable to start")}}
function setup(error=""){root.innerHTML=`<section class="setup"><div class="setup-card"><div class="app-mark">AM</div><p class="eyebrow">Sales force</p><h1>Ai Matic Sales</h1><p>Connect securely to ERPNext to create and track customer orders.</p>${error?`<p class="alert danger">${esc(error)}</p>`:""}<form id="setup"><label>ERPNext URL<input id="url" type="url" required placeholder="https://erp.example.com" autocomplete="url"></label><button class="primary">Continue</button></form><small>v${esc(__APP_VERSION__)} · No API key or secret</small></div></section>`;document.querySelector<HTMLFormElement>("#setup")!.onsubmit=async(event)=>{event.preventDefault();try{await configure(document.querySelector<HTMLInputElement>("#url")!.value);signIn()}catch(reason){setup(reason instanceof Error?reason.message:"Connection failed")}}}
function signIn(){root.innerHTML=`<section class="setup"><div class="setup-card"><div class="app-mark">AM</div><p class="eyebrow">Secure access</p><h1>Salesperson sign in</h1><p>Use your individual ERPNext Sales User account. Your permissions remain enforced by ERPNext.</p>${message?`<p class="alert danger">${esc(message)}</p>`:""}<button id="login" class="primary wide">Sign in with ERPNext</button><button id="change-server" class="secondary wide">Change ERPNext server</button></div></section>`;document.querySelector<HTMLButtonElement>("#login")!.onclick=async()=>{try{await credentials!.login();await loadContext()}catch(error){message=error instanceof Error?error.message:"Sign in failed";signIn()}};document.querySelector<HTMLButtonElement>("#change-server")!.onclick=()=>void changeServer()}
async function loadContext(){loading="Loading your sales workspace";render();context=await payload(await api!.getContext(draft.branch||undefined,draft.warehouse||undefined));draft.branch||=text(context,"branch");draft.warehouse||=text(context,"warehouse");save(draft);loading="";render("customers");void syncQueued()}
async function findCustomers(query:string){const request=++customerSearchSequence;customerQuery=query;document.querySelector("#customer-form")?.setAttribute("aria-busy","true");try{const result=list((await payload(await api!.searchCustomers(query))).customers);if(request!==customerSearchSequence)return;customers=result;notice(customers.length?`${customers.length} customers found`:"No matching customers",customers.length?"info":"warning")}catch(error){if(request===customerSearchSequence)notice(error instanceof Error?error.message:"Customer search failed","danger")}finally{if(request===customerSearchSequence)render("customers")}}
async function selectCustomer(name:string){if(!draft.warehouse){notice("Select a warehouse before choosing a customer.","warning");return render("customers")}if(draft.customer&&draft.customer!==name&&draft.items.length&&!confirm(`Switching from ${currentCustomerName()} clears the ${draft.items.length} item(s) already in this order - pricing and stock are customer-specific. Continue?`))return;loading="Loading customer details";render();try{customer=await payload(await api!.getCustomerContext(name,draft.branch||undefined,draft.warehouse));draft=switchDraftCustomer(draft,name);save(draft);remember(recentCustomersKey,name);customers=[];products=[];itemIndex.clear();lastItemSearch="";preview=null;notice(`${currentCustomerName()} selected`,"success");screen="order";await findItems()}catch(error){loading="";notice(error instanceof Error?error.message:"Unable to select customer","danger");render("customers")}}
async function findItems(query="",barcode=""){const request=++itemSearchSequence,key=`${query}|${barcode}|${draft.branch}|${draft.warehouse}|${draft.customer}`;itemQuery=query;if(key===lastItemSearch&&products.length){render("order");return}if(!products.length){loading="Loading available items";render()}try{const result=await payload(await api!.searchItems({branch:draft.branch||undefined,warehouse:draft.warehouse||undefined,customer:draft.customer,search:query||undefined,barcode:barcode||undefined}));if(request!==itemSearchSequence)return;products=list(result.items);for(const product of products)itemIndex.set(text(product,"name","item_code"),product);lastItemSearch=key;notice(products.length?`${products.length} items available`:"No matching items",products.length?"info":"warning")}catch(error){if(request===itemSearchSequence)notice(error instanceof Error?error.message:"Item search failed","danger")}finally{if(request===itemSearchSequence){loading="";render("order")}}}

function header(){const queued=loadDrafts().filter((entry)=>entry.status==="queued").length;return `<header class="top"><button class="identity" data-screen="customers"><span>AM</span><div><strong>Ai Matic Sales</strong><small>${esc(text(context,"full_name","user")||"Sales workspace")}</small></div></button><div class="top-status"><span class="${navigator.onLine?"online":"offline"}">${navigator.onLine?"● Online":"↯ Offline"}</span>${queued?statusBadge(`${queued} queued`,"warning"):""}</div></header>`}
function nav(){const active=screen==="review"?"order":screen;return bottomNavigation<Exclude<Screen,"review">>("Sales navigation",active,[{id:"customers",label:"Customers",icon:"♟"},{id:"order",label:"Order",icon:"＋",badge:draft.items.length},{id:"drafts",label:"Drafts",icon:"▤",badge:loadDrafts().filter((entry)=>["draft","queued","failed"].includes(entry.status)).length},{id:"orders",label:"Orders",icon:"▣"},{id:"profile",label:"Profile",icon:"●"}])}
function alert(){return message?`<div class="alert ${messageTone}" role="status"><span>${messageTone==="danger"?"!":messageTone==="success"?"✓":"i"}</span><p>${esc(message)}</p></div>`:""}
function customerSummary(){
  if(!customer)return "";
  const outstanding=Number(customer.outstanding_balance||0),limit=Number(customer.credit_limit||0),available=Math.max(0,limit-outstanding);
  return `<section class="selected-customer"><div><span class="customer-avatar">${esc(currentCustomerName().slice(0,2).toUpperCase())}</span><div><small>Selected customer</small><h2>${esc(currentCustomerName())}</h2><p>${esc(text(customer,"territory")||"Territory not supplied")} · ${esc(text(customer,"price_list")||"Default price list")}</p></div></div><div class="credit-meter"><span><small>Outstanding</small><b>${money(outstanding)}</b></span><span><small>Credit available</small><b>${limit?money(available):"Not limited"}</b></span></div><button id="change-customer">Change</button></section>`}
function customersView(){
  const recent=readList(recentCustomersKey);
  const warehouses=list(context.warehouses);
  const warehouseChoice=warehouses.length>1||!draft.warehouse?`<label>Warehouse<select id="customer-warehouse" required><option value="">Select warehouse</option>${warehouses.map((entry)=>`<option value="${esc(text(entry,"name"))}" ${text(entry,"name")===draft.warehouse?"selected":""}>${esc(text(entry,"name"))}</option>`).join("")}</select></label>`:`<div class="context-value"><small>Warehouse</small><b>${esc(draft.warehouse)}</b></div>`;
  return `<section class="page"><div class="page-title"><div><p class="eyebrow">Start an order</p><h1>Choose customer</h1><p>Pricing, balance and credit context load with your selection.</p></div></div><div class="order-context customer-context"><div class="context-value"><small>Company</small><b>${esc(text(context,"company")||"ERPNext default")}</b></div>${warehouseChoice}</div>${!draft.warehouse?`<div class="alert warning"><span>!</span><p>Choose the warehouse whose stock this order will use.</p></div>`:""}${customerSummary()}<form id="customer-form" class="search-bar"><span>⌕</span><input id="customer-query" type="search" value="${esc(customerQuery)}" placeholder="Name, mobile, email or customer code" autocomplete="off"><button class="primary">Search</button></form>${recent.length?`<section class="content-section"><div class="section-title"><h2>Recent customers</h2></div><div class="recent-row">${recent.map((name)=>`<button class="recent-chip customer-pick" data-name="${esc(name)}">↺ ${esc(name)}</button>`).join("")}</div></section>`:""}<section class="content-section"><div class="section-title"><h2>${customers.length?"Search results":"Customers"}</h2><small>${customers.length?"Tap to select":"Search to view permitted customers"}</small></div><div class="customer-grid">${customers.map((entry)=>{const balanceKnown=entry.outstanding_balance!==undefined&&entry.outstanding_balance!==null,balance=Number(entry.outstanding_balance||0);return `<button class="customer-card customer-pick ${entry.name===draft.customer?"selected":""}" data-name="${esc(text(entry,"name"))}"><span class="customer-avatar">${esc(text(entry,"customer_name","name").slice(0,2).toUpperCase())}</span><span><strong>${esc(text(entry,"customer_name","name"))}</strong><small>${esc(text(entry,"mobile_no","territory")||"No contact supplied")}</small><small>${esc(text(entry,"price_list")||"Customer pricing")}</small></span><span class="customer-balance"><small>Balance</small><b>${balanceKnown?(balance?money(balance):"Clear"):"View details"}</b></span></button>`}).join("")||emptyState("♟","Find a customer","Search by name, mobile, email or customer code.")}</div></section></section>`
}
function productCard(product:Row){
  const code=text(product,"name","item_code"),stock=Number(product.available_qty||0),rate=Number(product.rate||0),line=draft.items.find((entry)=>entry.item_code===code);
  return `<article class="product-card ${stock<=0?"out":""}"><button class="product-main add" data-code="${esc(code)}" ${stock<=0?"disabled":""}><span class="product-icon">${esc(text(product,"item_name","name").slice(0,2).toUpperCase())}</span><span><small>${esc(text(product,"item_group","category")||code)}</small><strong>${esc(text(product,"item_name","name"))}</strong><span class="price">${money(rate)}</span><span class="stock ${stock<=0?"danger-text":stock<5?"warning-text":""}">${stock<=0?"Out of stock":`${stock} available`}</span></span></button><div class="quick-add">${line?`<button class="quick-qty" data-code="${esc(code)}" data-delta="-1" aria-label="Decrease quantity">−</button><input class="quick-qty-input" data-card-qty="${esc(code)}" type="number" min="0.001" step="any" inputmode="decimal" value="${line.qty}" aria-label="Quantity for ${esc(text(product,"item_name","name"))}"><button class="quick-qty" data-code="${esc(code)}" data-delta="1" aria-label="Increase quantity">+</button>`:`<button class="add" data-code="${esc(code)}" ${stock<=0?"disabled":""}>Add</button>`}</div></article>`
}
function orderView(){
  if(!draft.customer)return `<section class="page">${emptyState("♟","Select a customer first","Customer-specific pricing and stock require a customer.",{label:"Choose customer",attribute:'data-screen="customers"'})}</section>`;
  const categories=["All",...new Set(products.map((product)=>text(product,"item_group","category")).filter(Boolean))];
  const visible=products.filter((product)=>category==="All"||text(product,"item_group","category")===category);
  const recent=readList(recentItemsKey);
  const branches=list(context.branches),warehouses=list(context.warehouses);
  const branchControl=branches.length?`<label>Branch<select id="branch"><option value="">ERPNext default</option>${branches.map((branch)=>`<option value="${esc(text(branch,"name"))}" ${text(branch,"name")===draft.branch?"selected":""}>${esc(text(branch,"name"))}</option>`).join("")}</select></label>`:`<div class="context-value"><small>Company</small><b>${esc(text(context,"company")||"ERPNext default")}</b></div>`;
  const warehouseControl=warehouses.length>1?`<label>Warehouse<select id="warehouse">${warehouses.map((warehouse)=>`<option value="${esc(text(warehouse,"name"))}" ${text(warehouse,"name")===draft.warehouse?"selected":""}>${esc(text(warehouse,"name"))}</option>`).join("")}</select></label>`:`<div class="context-value"><small>Warehouse</small><b>${esc(draft.warehouse||text(context,"warehouse"))}</b></div>`;
  return `<section class="page order-page"><div class="page-title"><div><p class="eyebrow">Customer order</p><h1>Add items</h1><p>${esc(currentCustomerName())} · ${esc(text(customer||undefined,"price_list")||"Customer pricing")}</p></div><button class="cart-pill" data-screen="review"><span>${draft.items.length}</span> Review cart</button></div>${customerSummary()}<div class="order-context">${branchControl}${warehouseControl}<label>Delivery date<input id="delivery" type="date" value="${esc(draft.deliveryDate)}"></label></div><form id="item-form" class="search-bar"><span>⌕</span><input id="item-query" type="search" value="${esc(itemQuery)}" placeholder="Search item, code or category" autocomplete="off"><button id="scan" type="button" aria-label="Scan barcode">▣ Scan</button></form><div class="category-tabs">${categories.map((value)=>`<button data-category="${esc(value)}" ${value===category?'aria-selected="true"':""}>${esc(value)}</button>`).join("")}</div>${recent.length?`<div class="recent-row"><span>Recent</span>${recent.map((code)=>`<button class="recent-chip" data-item-search="${esc(code)}">${esc(code)}</button>`).join("")}</div>`:""}<div class="product-grid">${visible.map(productCard).join("")||emptyState("⌕","No items to show","Search the permitted catalogue or scan a barcode.")}</div></section><button class="cart-dock" data-screen="review"><span><b>${draft.items.reduce((sum,item)=>sum+item.qty,0)} items</b><small>${draft.status==="queued"?"Queued offline":"Local draft saved"}</small></span><strong>${money(estimate())}</strong><span>Review →</span></button>`
}
function reviewView(){
  const total=estimate(),tax=Number(preview?.total_taxes_and_charges||preview?.taxes||0),grand=Number(preview?.grand_total||total+tax);
  const outstanding=Number(customer?.outstanding_balance||0),limit=Number(customer?.credit_limit||0),creditWarning=Boolean(preview?.credit_warning)||(limit>0&&outstanding+grand>limit);
  return `<section class="page review-page"><div class="page-title"><div><button class="back-button" data-screen="order">‹ Items</button><p class="eyebrow">Order review</p><h1>Review before submission</h1></div>${statusBadge(draft.status,statusTone(draft.status))}</div>${customerSummary()}<section class="review-card"><div class="review-heading"><h2>Items</h2><button data-screen="order">+ Add more</button></div>${draft.items.map((item)=>{const product=itemIndex.get(item.item_code);const rate=Number(product?.rate||0),stock=Number(product?.available_qty??Number.POSITIVE_INFINITY);return `<article class="cart-line"><div><strong>${esc(text(product,"item_name")||item.item_code)}</strong><small>${esc(item.item_code)} · ${esc(item.uom||"Nos")}</small>${Number.isFinite(stock)&&item.qty>stock?`<span class="line-warning">! Only ${stock} available</span>`:""}</div><div class="quantity"><button data-cart-qty="${esc(item.item_code)}" data-delta="-1" aria-label="Decrease quantity">−</button><input data-qty-input="${esc(item.item_code)}" type="number" min="0.001" step="any" value="${item.qty}" inputmode="decimal" aria-label="Quantity"><button data-cart-qty="${esc(item.item_code)}" data-delta="1" aria-label="Increase quantity">+</button></div><div class="line-total"><small>${money(rate)} each</small><b>${money(rate*item.qty)}</b></div></article>`}).join("")||emptyState("＋","No items yet","Return to the catalogue and add products.")}</section>${creditWarning?`<div class="alert warning"><span>!</span><p>Credit limit warning. ERPNext will apply the authoritative validation.</p></div>`:""}<section class="review-grid"><div class="review-card"><h2>Order details</h2><label>Delivery date<input id="delivery" type="date" value="${esc(draft.deliveryDate)}"></label><label>Customer PO<input id="po" value="${esc(draft.poNo)}" placeholder="Optional reference"></label><label>Notes<textarea id="remarks" rows="3" placeholder="Delivery or sales notes">${esc(draft.remarks)}</textarea></label></div><aside class="totals-card"><h2>Summary</h2><p><span>Displayed estimate</span><b>${money(total)}</b></p><p><span>ERPNext tax</span><b>${preview?money(tax):"Refresh required"}</b></p><p class="grand"><span>Grand total</span><strong>${preview?money(grand):money(total)}</strong></p><small>${preview?"Validated with ERPNext pricing.":"Refresh totals before final submission."}</small><button id="preview" class="secondary wide" ${submitting?"disabled":""}>↻ Refresh ERPNext total</button><button id="save-draft" class="secondary wide" ${submitting?"disabled":""}>Save local draft</button><button id="submit" class="primary wide" ${!draft.items.length||submitting?"disabled":""}>${submitting?"Creating order…":"Create Sales Order"}</button></aside></section></section>`
}
function draftsView(){
  const all=loadDrafts().filter((entry)=>entry.status!=="submitted");
  return `<section class="page"><div class="page-title"><div><p class="eyebrow">Offline workspace</p><h1>Drafts & sync queue</h1><p>Every status is explicit; retries retain the original request ID.</p></div><button id="sync" class="primary" ${navigator.onLine&&!syncPromise?"":"disabled"}>${syncPromise?"Synchronizing…":"↻ Sync queued"}</button></div><div class="draft-list">${all.map((entry)=>`<article class="draft-card ${entry.status}" aria-busy="${entry.status==="syncing"}"><div><span class="draft-icon">${entry.status==="syncing"?"↻":entry.status==="queued"?"↯":entry.status==="failed"?"!":"✎"}</span><div><strong>${esc(entry.customer||"Unassigned draft")}</strong><small>${entry.items.length} lines · Updated ${new Date(entry.updatedAt).toLocaleString()}</small><small>Request ${esc(entry.requestId.slice(0,8))}…</small></div></div>${statusBadge(entry.status,statusTone(entry.status))}${entry.error?`<p>${esc(entry.error)}</p>`:""}<div><button class="load secondary" data-id="${esc(entry.requestId)}" ${entry.status==="syncing"?"disabled":""}>Open draft</button>${entry.status==="failed"||entry.status==="queued"?`<button class="retry primary" data-id="${esc(entry.requestId)}" ${navigator.onLine&&!syncPromise?"":"disabled"}>Retry safely</button>`:""}</div></article>`).join("")||emptyState("✓","No pending drafts","Local drafts, queued orders and failed sync attempts appear here.")}</div></section>`
}
function ordersView(){
  const filters=["All","Draft","Submitted","Partially Delivered","Completed","Cancelled"];
  const visible=history.filter((entry)=>orderFilter==="All"||text(entry,"status","delivery_status").toLowerCase().includes(orderFilter.toLowerCase()));
  return `<section class="page"><div class="page-title"><div><p class="eyebrow">ERPNext orders</p><h1>Order history</h1><p>Server-confirmed order state and delivery progress.</p></div><button id="refresh-orders" class="secondary">↻ Refresh</button></div><div class="filter-tabs">${filters.map((filter)=>`<button data-order-filter="${filter}" ${filter===orderFilter?'aria-selected="true"':""}>${filter}</button>`).join("")}</div><div class="history-list">${visible.map((entry)=>`<article><div><strong>${esc(text(entry,"name"))}</strong><small>${esc(text(entry,"customer_name","customer"))} · ${esc(text(entry,"transaction_date","creation"))}</small></div>${statusBadge(text(entry,"delivery_status","status")||"Draft",statusTone(text(entry,"status")))}<b>${money(entry.grand_total)}</b><button data-order-detail="${esc(text(entry,"name"))}">View →</button></article>`).join("")||emptyState("▣","No matching orders","Refresh history or choose another status filter.")}</div></section>`
}
function profileView(){const queued=loadDrafts().filter((entry)=>entry.status==="queued").length;return `<section class="page"><div class="profile-card"><span class="profile-avatar">${esc(text(context,"full_name","user").slice(0,2).toUpperCase())}</span><div><p class="eyebrow">Sales profile</p><h1>${esc(text(context,"full_name","user"))}</h1><p>${esc(text(context,"territory")||"ERPNext Sales User")}</p></div>${statusBadge(navigator.onLine?"Online":"Offline",navigator.onLine?"success":"warning")}</div><div class="profile-grid"><section><h2>Workspace</h2><p><span>Company</span><b>${esc(text(context,"company")||"ERPNext default")}</b></p><p><span>Branch</span><b>${esc(draft.branch||"Not required")}</b></p><p><span>Warehouse</span><b>${esc(draft.warehouse||text(context,"warehouse"))}</b></p><p><span>Drafts on device</span><b>${loadDrafts().filter((entry)=>entry.status==="draft").length}</b></p><p><span>Queued for sync</span><b>${queued}</b></p><p><span>App version</span><b>v${esc(__APP_VERSION__)}</b></p></section><section><h2>Security & server</h2><p>Authentication and permissions are enforced by ERPNext. Prices, credit and stock are never client-authoritative.</p><p><span>Connected to</span><b>${esc(config?.baseUrl||"")}</b></p><button id="logout" class="secondary wide">Sign out securely</button><button id="change-server" class="secondary wide">Change ERPNext server</button></section></div></section>`}
function render(next:Screen=screen){
  screen=next;
  if(!context.user&&!context.full_name&&loading){root.innerHTML=`<section class="setup"><div class="setup-card">${loadingSkeleton(4)}<p>${esc(loading)}</p></div></section>`;return}
  const content=loading?`<section class="page">${loadingSkeleton(5)}<p class="loading-label">${esc(loading)}</p></section>`:screen==="customers"?customersView():screen==="order"?orderView():screen==="review"?reviewView():screen==="drafts"?draftsView():screen==="orders"?ordersView():profileView();
  root.innerHTML=`${header()}${alert()}${content}${nav()}`;bind()
}
function updateForm(){draft={...draft,branch:document.querySelector<HTMLSelectElement>("#branch")?.value??draft.branch,warehouse:document.querySelector<HTMLSelectElement>("#warehouse")?.value||draft.warehouse,deliveryDate:document.querySelector<HTMLInputElement>("#delivery")?.value||draft.deliveryDate,poNo:document.querySelector<HTMLInputElement>("#po")?.value||draft.poNo,remarks:document.querySelector<HTMLTextAreaElement>("#remarks")?.value||draft.remarks};save(draft)}
function addProduct(code:string,delta=1){const product=itemIndex.get(code)||products.find((entry)=>text(entry,"name","item_code")===code);if(!product)return;const old=draft.items.find((entry)=>entry.item_code===code);draft=setDraftItem(draft,{item_code:code,qty:(old?.qty||0)+delta,uom:text(product,"stock_uom","uom")||old?.uom});save(draft);preview=null;remember(recentItemsKey,code);notice(delta>0?`${text(product,"item_name","name")} added`:"Quantity updated","success");render(screen)}
async function loadOrders(){loading="Loading server orders";render();try{history=list((await payload(await api!.getOrders())).orders);notice(`${history.length} orders loaded`,"success")}catch(error){notice(error instanceof Error?error.message:"Unable to load orders","danger")}finally{loading="";render("orders")}}
function bind(){
  document.querySelectorAll<HTMLButtonElement>("[data-screen]").forEach((button)=>button.onclick=()=>{const next=button.dataset.screen as Screen;if(next==="orders")void loadOrders();else render(next)});
  document.querySelector<HTMLFormElement>("#customer-form")?.addEventListener("submit",(event)=>{event.preventDefault();void findCustomers(document.querySelector<HTMLInputElement>("#customer-query")!.value)});
  document.querySelector<HTMLInputElement>("#customer-query")?.addEventListener("input",(event)=>{window.clearTimeout(searchTimer);const query=(event.target as HTMLInputElement).value;customerQuery=query;if(query.length>=2)searchTimer=window.setTimeout(()=>void findCustomers(query),300)});
  document.querySelectorAll<HTMLButtonElement>(".customer-pick").forEach((button)=>button.onclick=()=>void selectCustomer(button.dataset.name!));
  document.querySelector<HTMLSelectElement>("#customer-warehouse")?.addEventListener("change",async(event)=>{const warehouse=(event.target as HTMLSelectElement).value;draft={...draft,warehouse};save(draft);products=[];itemIndex.clear();lastItemSearch="";preview=null;if(!warehouse){notice("Select a warehouse to continue.","warning");return render("customers")}loading="Applying warehouse";render();try{context=await payload(await api!.getContext(draft.branch||undefined,warehouse));draft.warehouse=text(context,"warehouse")||warehouse;save(draft);notice(`${draft.warehouse} selected.`,"success")}catch(error){draft.warehouse="";save(draft);notice(error instanceof Error?error.message:"Unable to select warehouse","danger")}finally{loading="";render("customers")}});
  document.querySelector<HTMLButtonElement>("#change-customer")?.addEventListener("click",()=>{if(draft.items.length&&!confirm(`Changing customer clears the ${draft.items.length} item(s) already in this order for ${currentCustomerName()}. Continue?`))return;customer=null;draft=switchDraftCustomer(draft,"");products=[];itemIndex.clear();lastItemSearch="";itemQuery="";preview=null;save(draft);render("customers")});
  document.querySelector<HTMLSelectElement>("#branch")?.addEventListener("change",async()=>{if(draft.items.length&&!confirm(`Changing branch clears the ${draft.items.length} item(s) already in this order - stock and pricing are branch-specific. Continue?`)){render();return}updateForm();customer=null;draft={...draft,customer:"",warehouse:"",items:[]};products=[];itemIndex.clear();lastItemSearch="";preview=null;save(draft);loading="Applying ERPNext defaults";render();try{context=await payload(await api!.getContext(draft.branch||undefined));draft.warehouse=text(context,"warehouse");save(draft);notice("Branch context updated. Select the customer again.","success")}catch(error){notice(error instanceof Error?error.message:"Unable to change branch","danger")}finally{loading="";render("customers")}});
  document.querySelector<HTMLSelectElement>("#warehouse")?.addEventListener("change",()=>{updateForm();products=[];itemIndex.clear();lastItemSearch="";preview=null;notice("Warehouse changed. Stock will refresh.","success");void findItems()});
  document.querySelector<HTMLFormElement>("#item-form")?.addEventListener("submit",(event)=>{event.preventDefault();void findItems(document.querySelector<HTMLInputElement>("#item-query")!.value)});
  document.querySelector<HTMLInputElement>("#item-query")?.addEventListener("input",(event)=>{window.clearTimeout(searchTimer);const query=(event.target as HTMLInputElement).value;itemQuery=query;searchTimer=window.setTimeout(()=>void findItems(query),300)});
  document.querySelector<HTMLButtonElement>("#scan")?.addEventListener("click",async()=>{try{await findItems("",await scanItemBarcode())}catch(error){notice(error instanceof Error?error.message:"Scan failed","danger");render()}});
  document.querySelectorAll<HTMLButtonElement>("[data-category]").forEach((button)=>button.onclick=()=>{category=button.dataset.category||"All";render()});
  document.querySelectorAll<HTMLButtonElement>("[data-item-search]").forEach((button)=>button.onclick=()=>void findItems(button.dataset.itemSearch));
  document.querySelectorAll<HTMLButtonElement>(".add").forEach((button)=>button.onclick=()=>addProduct(button.dataset.code!));
  document.querySelectorAll<HTMLButtonElement>(".quick-qty,[data-cart-qty]").forEach((button)=>button.onclick=()=>addProduct(button.dataset.code||button.dataset.cartQty!,Number(button.dataset.delta)));
  document.querySelectorAll<HTMLInputElement>("[data-card-qty]").forEach((input)=>{const apply=()=>{const code=input.dataset.cardQty!,old=draft.items.find((entry)=>entry.item_code===code);if(!old)return;const qty=Number(input.value);if(!Number.isFinite(qty)||qty<=0){input.value=String(old.qty);notice("Enter a quantity greater than zero.","warning");return render("order")}draft=setDraftItem(draft,{...old,qty});save(draft);preview=null;notice("Quantity updated.","success");render("order")};input.onchange=apply;input.onkeydown=(event)=>{if(event.key==="Enter"){event.preventDefault();apply()}}});
  document.querySelectorAll<HTMLInputElement>("[data-qty-input]").forEach((input)=>input.onchange=()=>{const old=draft.items.find((entry)=>entry.item_code===input.dataset.qtyInput)!;const qty=Number(input.value);if(!Number.isFinite(qty)||qty<=0){notice("Enter a quantity greater than zero.","warning");return render("review")}draft=setDraftItem(draft,{...old,qty});save(draft);preview=null;render("review")});
  document.querySelector<HTMLButtonElement>("#save-draft")?.addEventListener("click",()=>{updateForm();notice("Draft saved safely on this device.","success");render()});
  document.querySelector<HTMLButtonElement>("#preview")?.addEventListener("click",()=>void previewOrder());
  document.querySelector<HTMLButtonElement>("#submit")?.addEventListener("click",()=>void submitOrder());
  document.querySelectorAll<HTMLButtonElement>(".load").forEach((button)=>button.onclick=()=>void resumeDraft(button.dataset.id!));
  document.querySelectorAll<HTMLButtonElement>(".retry").forEach((button)=>button.onclick=()=>void syncQueued(true,button.dataset.id));
  document.querySelector<HTMLButtonElement>("#sync")?.addEventListener("click",()=>void syncQueued(true));
  document.querySelector<HTMLButtonElement>("#refresh-orders")?.addEventListener("click",()=>void loadOrders());
  document.querySelectorAll<HTMLButtonElement>("[data-order-filter]").forEach((button)=>button.onclick=()=>{orderFilter=button.dataset.orderFilter||"All";render()});
  document.querySelectorAll<HTMLButtonElement>("[data-order-detail]").forEach((button)=>button.onclick=()=>{notice(`Order ${button.dataset.orderDetail} is server-confirmed. Detailed timeline depends on delivery data from ERPNext.`,"info");render()});
  document.querySelector<HTMLButtonElement>("#logout")?.addEventListener("click",async()=>{await credentials!.clear();context={};message="";signIn()});
  document.querySelector<HTMLButtonElement>("#change-server")?.addEventListener("click",()=>void changeServer());
}
function requestBody(value:SalesDraft){return{request_id:value.requestId,branch:value.branch||undefined,warehouse:value.warehouse||undefined,customer:value.customer,items:value.items,delivery_date:value.deliveryDate,po_no:value.poNo,remarks:value.remarks}}
async function resumeDraft(id:string){const saved=loadDrafts().find((entry)=>entry.requestId===id);if(!saved)return;draft=saved;localStorage.setItem(activeDraftKey,JSON.stringify(saved));customer=null;products=[];itemIndex.clear();lastItemSearch="";itemQuery="";message="";if(!draft.customer)return render("customers");loading="Restoring customer pricing and item availability";render();try{context=await payload(await api!.getContext(draft.branch||undefined,draft.warehouse||undefined));customer=await payload(await api!.getCustomerContext(draft.customer,draft.branch||undefined,draft.warehouse));const results=await Promise.all(draft.items.map((item)=>api!.searchItems({branch:draft.branch||undefined,warehouse:draft.warehouse||undefined,customer:draft.customer,search:item.item_code,limit:10}).then(payload).catch(()=>({items:[]}))));for(const result of results)for(const product of list(result.items)){const code=text(product,"name","item_code");itemIndex.set(code,product);if(!products.some((entry)=>text(entry,"name","item_code")===code))products.push(product)}notice("Draft restored with current ERPNext pricing and stock.","success")}catch(error){notice(error instanceof Error?error.message:"Draft restored, but live details could not be refreshed.","warning")}finally{loading="";render("review")}}
async function previewOrder(){try{updateForm();assertSalesDraftReady(draft);loading="Validating pricing, stock and credit";render();preview=await payload(await api!.previewOrder(requestBody(draft)));notice("ERPNext totals refreshed.","success")}catch(error){notice(error instanceof Error?error.message:"Preview failed","danger")}finally{loading="";render("review")}}
async function submitOrder(){if(submitting)return;submitting=true;try{updateForm();assertSalesDraftReady(draft);render("review");const result=await payload(await api!.createOrder(requestBody(draft)));save(markDraft(draft,"submitted",{salesOrder:text(result,"sales_order"),error:undefined}));notice(`Order ${text(result,"sales_order")} created successfully.`,"success");preview=null;draft=newSalesDraft(text(context,"branch"),new Date(),text(context,"warehouse"));save(draft);await loadOrders()}catch(error){const reason=error instanceof Error?error.message:"Network error",networkFailure=!navigator.onLine||error instanceof TypeError;save(markDraft(draft,networkFailure?"queued":"failed",{error:reason}));notice(networkFailure?"Order queued safely and will sync when online.":reason,networkFailure?"warning":"danger");render("drafts")}finally{submitting=false}}
async function syncQueued(show=false,onlyId?:string){if(syncPromise)return syncPromise;const run=async()=>{let count=0,failed=0;const candidates=loadDrafts().filter((item)=>onlyId?item.requestId===onlyId&&["queued","failed"].includes(item.status):item.status==="queued");for(const entry of candidates){save(markDraft(entry,"syncing",{error:undefined}),false);if(screen==="drafts")render("drafts");try{const result=await payload(await api!.createOrder(requestBody(entry)));save(markDraft(entry,"submitted",{salesOrder:text(result,"sales_order"),error:undefined}),false);count++}catch(error){/* original request ID and failure state remain visible until a confirmed retry */const reason=error instanceof Error?error.message:"Synchronization failed",networkFailure=!navigator.onLine||error instanceof TypeError;save(markDraft(entry,networkFailure?"queued":"failed",{error:reason}),false);failed++}}if(show||failed){notice(count&& !failed?`${count} order${count===1?"":"s"} synchronized safely.`:failed?`${failed} order${failed===1?"":"s"} still need attention.`:"No queued orders to synchronize.",failed?"warning":count?"success":"info")}if(screen==="drafts")render("drafts")};syncPromise=run().finally(()=>{syncPromise=null;if(screen==="drafts")render("drafts")});return syncPromise}
async function changeServer(){if(loadDrafts().some((entry)=>entry.items.length&&entry.status!=="submitted")&&!confirm("Local drafts and queued orders belong to this ERPNext server. Change server and remove local Sales data?"))return;await credentials?.clear();for(const key of [configKey,draftsKey,activeDraftKey,recentCustomersKey,recentItemsKey])localStorage.removeItem(key);draftStore=[];draft=newSalesDraft();context={};customer=null;customers=[];products=[];history=[];itemIndex.clear();config=null;credentials=null;api=null;message="";setup()}
window.addEventListener("online",()=>{notice("Connection restored. Queued orders can synchronize now.","success");render(screen);void syncQueued()});
window.addEventListener("offline",()=>{notice("Offline. New submissions will remain safely queued on this device.","warning");render(screen)});
void start();
